### ISSUE TITLE
Ammo not spawn

### ISSUE THREAD

**Issue by Barna13** [RogerFK/SMOD2-ItemSpawner#3]
Hi,
DROPPED_9, DROPPED_7, DROPPED_5, doesn't spawn with your plugin, is it normal ?
Thank you,
Gaby

**Comment by agent188** [comment]
![image](https://user-images.githubusercontent.com/41228098/61029604-14d60a80-a3c4-11e9-9f3b-1e87d015f024.png)
In the items.txt file, move the "Y" coordinate a little higher.

**Comment by Barna13** [comment]
I finally found the problem, I put "disable_dropping_empty_boxes" to false and it work
